name: "PRODUCTION ENV: DBT Snowflake Workflow"

on:
  push:
    branches:
      - main # Change this to your main branch name
  pull_request:
  workflow_dispatch: # Manually triggered workflow

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    env:
      SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
      DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
      DBT_USER: ${{ secrets.DBT_USER }}
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42


      - name: Build only the modified dbt models
        id: build_test
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          list_of_models="";
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
            if [[ $file == *.sql ]]; then
              if [ -z "$sql_files" ]; then
                list_of_models="$(basename $file .sql)"
              else
                list_of_models="list_of_models,$(basename $file .sql)"
              fi
            fi
          done
          echo "dbt build -m $list_of_models"

        continue-on-error: true

